apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "org-token-tool"
  namespace: "org"
  labels:
    "team": "team org"
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - "https://org-token-tool.intern.nav.no"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  liveness:
    path: /internal/health/liveness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  env:
    - name: NODE_ENV
      value: "production"
  azure:
    application:
      enabled: true
      tenant: nav.no
      singlePageApplication: true
      allowAllUsers: false
      claims:
        groups:
          - id: efa3b907-b01c-4293-94a2-c0890b123783
    sidecar:
      enabled: true
      autoLogin: true
