name: org-token-tool

on:
  push:
    branches:
      - 'main'
      - 'dev/*'

jobs:
  build:
    name: "Build app and push docker image to GAR"
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'

      - name: Install webapp dependencies
        run: yarn install

      - name: Build webapp
        run: yarn build

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: org
          dockerfile: Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-dev:
    name: Deploy dev-gcp
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/org-token-tool-dev.yaml
          VAR: image=${{needs.build.outputs.image}}

  deploy-prod:
    name: Deploy prod-gcp
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/org-token-tool-prod.yaml
          VAR: image=${{needs.build.outputs.image}}
