name: org-token-tool

on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/${{ github.repository }}/org-token-tool:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/${{ github.repository }}/org-token-tool:latest

jobs:
  build:
    name: Build and push docker, org-token-tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }},${{ env.IMAGE_LATEST }}

  deploy-dev:
    name: Deploy dev-gcp
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/org-token-tool-dev.yaml

  deploy-prod:
    name: Deploy prod-gcp
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/org-token-tool-prod.yaml
